### ISSUE TITLE
[question] Attachments

### ISSUE THREAD

**Issue by dominiksr** [reflexsoar/reflex#23]
Due to the fact that no one is responding to my emails I thought I would write here. When will the functionality of attachments in incidents appear? Currently I see that there is a button described as Comming soon. Overall reflexsoar is a very interesting and good solution but without this functionality it is practically useless to me.

PS. Do you have a discord or something like that?

**Comment by n3tsurge** [comment]
Sorry, what email were you emailing so I can make sure it's monitored a little better?  As for file attachments in cases, we have a release coming soon that adds new functionality and then we were going to overhaul cases and bolster that functionality so if I had to estimate it would be end of year early next.  I agree it is something that is sorely missing and necessary.

We don't have a Discord or Gitter or anything yet I have plans to create one however.

**Comment by n3tsurge** [comment]
See https://github.com/reflexsoar/reflex-api/issues/291 also created a Discord server hopefully will get more community users in here shortly but I am parked in it if you have more questions https://discord.gg/ZuNFAFHs4y

**Comment by dominiksr** [comment]
thank you. Currently I don't have time to spare. But I will definitely take a look in the future and ask a few things to clear my doubts.
